version: "3.9"
services:
    web:
        depends_on:
            - "redis_cache"
        build: .
        ports:
            - "5000:5000"
        links:
            - "redis_cache"
        environment:
            - RedisConnection=redis_cache
    redis_cache:
        image: "redis:alpine"
        ports:
            - "6379:6379"
